// G₂ root system and Coxeter group in simple-root coordinates, exact integers.
// Inner products: (α₁,α₁) = 2 (short), (α₂,α₂) = 6 (long), (α₁,α₂) = −3.
const G = [[2, -3], [-3, 6]];
export const ip = (a, b) => a[0] * (G[0][0] * b[0] + G[0][1] * b[1]) + a[1] * (G[1][0] * b[0] + G[1][1] * b[1]);
const SIMPLE = [[1, 0], [0, 1]];
// reflection in α: β ↦ β − (2(β,α)/(α,α)) α  (integral for a root system)
export const reflect = (beta, alpha) => {
  const c = (2 * ip(beta, alpha)) / ip(alpha, alpha);
  return [beta[0] - c * alpha[0], beta[1] - c * alpha[1]];
};
const key = v => v.join(',');
export function roots() {
  const seen = new Map(SIMPLE.map(r => [key(r), r])); const queue = [...SIMPLE];
  while (queue.length) {
    const b = queue.pop();
    for (const a of SIMPLE) { const r = reflect(b, a); if (!seen.has(key(r))) { seen.set(key(r), r); queue.push(r); } }
  }
  return [...seen.values()];
}
// Weyl group as 2×2 integer matrices acting on coordinates.
const matOf = alpha => { const c0 = reflect([1, 0], alpha), c1 = reflect([0, 1], alpha); return [[c0[0], c1[0]], [c0[1], c1[1]]]; };
const mm = (A, B) => [[A[0][0] * B[0][0] + A[0][1] * B[1][0], A[0][0] * B[0][1] + A[0][1] * B[1][1]], [A[1][0] * B[0][0] + A[1][1] * B[1][0], A[1][0] * B[0][1] + A[1][1] * B[1][1]]];
const mkey = M => M.flat().join(',');
export function weylGroup(gens) {
  const I = [[1, 0], [0, 1]]; const seen = new Map([[mkey(I), I]]); const q = [I];
  while (q.length) { const x = q.pop(); for (const g of gens) { const y = mm(g, x); if (!seen.has(mkey(y))) { seen.set(mkey(y), y); q.push(y); } } }
  return [...seen.values()];
}
export function orderOf(M) { let X = M, k = 1; while (mkey(X) !== '1,0,0,1') { X = mm(X, M); k++; if (k > 100) return -1; } return k; }
export function report() {
  const R = roots();
  const short = R.filter(r => ip(r, r) === 2), long = R.filter(r => ip(r, r) === 6);
  const isRoot = v => R.some(r => key(r) === key(v));
  const isLong = v => long.some(r => key(r) === key(v));
  // long roots closed under addition within the root system (a closed subsystem)
  const longClosed = long.every(a => long.every(b => { const s = [a[0] + b[0], a[1] + b[1]]; return !isRoot(s) || isLong(s); }));
  // the long subsystem is A₂: a closed rank-2 subsystem with 6 roots of one length
  // can only be A₂ (A₁×A₁ has 4, B₂ 8, G₂ 12); the −3 pairing (120°) confirms it
  const longIsA2 = long.length === 6 && long.some(a => long.some(b => ip(a, b) === -3));
  // any group generated by two involutions is dihedral of order 2·ord(s₁s₂);
  // so order 12 with ord(s₁s₂) = 6 is the dihedral group of the hexagon
  const W = weylGroup(SIMPLE.map(matOf));
  const cox = orderOf(mm(matOf(SIMPLE[0]), matOf(SIMPLE[1])));
  // Weyl group of the long subsystem (SU(3)'s Weyl group S₃) acting on the short roots:
  const WA2 = weylGroup(long.map(matOf));
  const apply = (M, v) => [M[0][0] * v[0] + M[0][1] * v[1], M[1][0] * v[0] + M[1][1] * v[1]];
  // split short roots into two orbits under W(A₂): the pattern of the weights
  // of 3 and 3̄ (orbit structure proved here; the identification is standard)
  const orbits = []; const done = new Set();
  for (const s of short) {
    if (done.has(key(s))) continue;
    const orb = new Map(); for (const M of WA2) { const t = apply(M, s); orb.set(key(t), t); }
    for (const k of orb.keys()) done.add(k); orbits.push([...orb.values()]);
  }
  const tripletPair = orbits.length === 2 && orbits.every(o => o.length === 3) &&
    orbits.every(o => o.reduce((acc, v) => [acc[0] + v[0], acc[1] + v[1]], [0, 0]).every(x => x === 0)) &&
    orbits[0].every(v => orbits[1].some(w => w[0] === -v[0] && w[1] === -v[1]));
  return {
    nRoots: R.length, nShort: short.length, nLong: long.length, lengthRatioSquared: 6 / 2,
    longClosed, longIsA2, weylOrder: W.length, weylA2Order: WA2.length, coxeterNumber: cox,
    dim: R.length + 2, tripletPair, rootsTimesH: 2 * cox, dimFormula: 2 * (cox + 1),
  };
}
