// Finite checks for notes/no-nothing-no-thing.md and wiki W-0014–W-0018.
// Everything here is elementary arithmetic or finite group/lattice
// enumeration; none of it computes a stable homotopy group from scratch.
// What it does check: the finite facts the stable-homotopy readings lean on.

// ---------- permutations ----------
export function perms(n) {
  if (n === 0) return [[]];
  const out = [];
  for (const p of perms(n - 1)) {
    for (let i = 0; i <= p.length; i++) {
      const q = p.slice(); q.splice(i, 0, n - 1); out.push(q);
    }
  }
  return out;
}
export const compose = (p, q) => q.map(i => p[i]); // (p∘q)(i) = p(q(i))
export const inverse = p => { const r = []; p.forEach((v, i) => { r[v] = i; }); return r; };
const key = p => p.join(',');

export function sign(p) {
  let s = 1; const seen = new Array(p.length).fill(false);
  for (let i = 0; i < p.length; i++) {
    if (seen[i]) continue;
    let len = 0, j = i;
    while (!seen[j]) { seen[j] = true; j = p[j]; len++; }
    if (len % 2 === 0) s = -s;
  }
  return s;
}

// Subgroup generated by a set of elements (closure under composition).
export function closure(gens, n) {
  const id = [...Array(n).keys()];
  const seen = new Map([[key(id), id]]);
  const queue = [id];
  while (queue.length) {
    const x = queue.pop();
    for (const g of gens) {
      const y = compose(g, x);
      if (!seen.has(key(y))) { seen.set(key(y), y); queue.push(y); }
    }
  }
  return [...seen.values()];
}

// |Σ_n^ab| = |Σ_n| / |[Σ_n, Σ_n]|.
export function abelianizationOrder(n) {
  const G = perms(n);
  if (G.length === 1) return 1;
  const comms = [];
  for (const a of G) for (const b of G) {
    comms.push(compose(compose(a, b), compose(inverse(a), inverse(b))));
  }
  const uniq = [...new Map(comms.map(c => [key(c), c])).values()];
  return G.length / closure(uniq, n).length;
}

export function signIsHomomorphism(n) {
  const G = perms(n);
  return G.every(a => G.every(b => sign(compose(a, b)) === sign(a) * sign(b)));
}

// ---------- exact rationals and Bernoulli numbers ----------
const gcd = (a, b) => { a = a < 0n ? -a : a; b = b < 0n ? -b : b; while (b) [a, b] = [b, a % b]; return a; };
export function rat(n, d = 1n) {
  n = BigInt(n); d = BigInt(d);
  if (d < 0n) { n = -n; d = -d; }
  const g = gcd(n, d) || 1n; return [n / g, d / g];
}
const add = ([a, b], [c, d]) => rat(a * d + c * b, b * d);
const mul = ([a, b], [c, d]) => rat(a * c, b * d);
const div = ([a, b], [c, d]) => rat(a * d, b * c);
const binom = (n, k) => { let r = 1n; for (let i = 1n; i <= BigInt(k); i++) r = r * (BigInt(n) - i + 1n) / i; return r; };

// B_0..B_m with B_1 = −1/2 (the value is irrelevant for even indices).
export function bernoulli(m) {
  const B = [rat(1)];
  for (let n = 1; n <= m; n++) {
    let s = rat(0);
    for (let k = 0; k < n; k++) s = add(s, mul(rat(binom(n + 1, k)), B[k]));
    B.push(div(mul(rat(-1), s), rat(n + 1)));
  }
  return B;
}

// Adams: |im J| in stem 4k−1 is the denominator of B_{2k}/(4k).
// Eisenstein: E_{2k} = 1 − (4k/B_{2k}) Σ σ_{2k−1}(n) qⁿ.
export function imJAndEisenstein(kMax) {
  const B = bernoulli(2 * kMax);
  const rows = [];
  for (let k = 1; k <= kMax; k++) {
    const b = B[2 * k];
    const [num, den] = div(b, rat(4 * k));
    const eis = div(rat(-4 * k), b); // may be non-integral
    rows.push({ k, stem: 4 * k - 1, imJ: den, bOver4kNumerator: num, eisenstein: eis });
  }
  return rows;
}

// ---------- the E8 lattice ----------
// E8 = { x ∈ ℤ⁸ ∪ (ℤ+½)⁸ : Σxᵢ ≡ 0 mod 2 }. Work with y = 2x (integers).
export function e8CountByNorm(maxNorm) {
  // norm(x) = Σ xᵢ² = Σ yᵢ²/4; count vectors with norm 2m for m = 1..maxNorm/2.
  const counts = new Map();
  const R = Math.floor(2 * Math.sqrt(maxNorm)); // |yᵢ| ≤ 2√maxNorm
  const y = new Array(8);
  function rec(i, parity, sumSq, sum) {
    if (sumSq > 4 * maxNorm) return;
    if (i === 8) {
      if (sumSq === 0) return;
      if (sum % 4 !== 0) return; // Σxᵢ = Σyᵢ/2 must be even
      const norm = sumSq / 4;
      counts.set(norm, (counts.get(norm) || 0) + 1);
      return;
    }
    for (let v = -R; v <= R; v++) {
      if ((((v % 2) + 2) % 2) !== parity) continue;
      y[i] = v; rec(i + 1, parity, sumSq + v * v, sum + v);
    }
  }
  rec(0, 0, 0, 0); // integer vectors
  rec(0, 1, 0, 0); // half-integer vectors
  return counts;
}
export const sigma = (s, n) => { let t = 0; for (let d = 1; d <= n; d++) if (n % d === 0) t += d ** s; return t; };

// ---------- invariant priors on finite G-sets ----------
// A G-set is given by generators acting as permutations of {0..m−1}.
export function orbits(gens, m) {
  const parent = [...Array(m).keys()];
  const find = x => (parent[x] === x ? x : (parent[x] = find(parent[x])));
  for (const g of gens) for (let i = 0; i < m; i++) parent[find(i)] = find(g[i]);
  return new Set([...Array(m).keys()].map(find)).size;
}
// Dimension of { v ∈ ℚ^m : v∘g = v for all generators } by Gaussian elimination.
export function invariantDimension(gens, m) {
  const rows = [];
  for (const g of gens) for (let i = 0; i < m; i++) {
    if (g[i] === i) continue;
    const r = new Array(m).fill(0); r[i] = 1; r[g[i]] -= 1; rows.push(r);
  }
  let rank = 0;
  const M = rows.map(r => r.slice());
  for (let c = 0; c < m && rank < M.length; c++) {
    let p = M.findIndex((r, idx) => idx >= rank && r[c] !== 0);
    if (p < 0) continue;
    [M[rank], M[p]] = [M[p], M[rank]];
    for (let r = 0; r < M.length; r++) {
      if (r !== rank && M[r][c] !== 0) {
        const f = M[r][c] / M[rank][c];
        for (let k = 0; k < m; k++) M[r][k] -= f * M[rank][k];
      }
    }
    rank++;
  }
  return m - rank;
}
// Burnside's lemma: #orbits = (1/|G|) Σ_g |X^g|, with the full group listed.
export function burnsideCount(groupElements, action) {
  let t = 0;
  for (const g of groupElements) { const a = action(g); t += a.filter((v, i) => v === i).length; }
  return t / groupElements.length;
}

// Kervaire–Milnor: |bP_{4k}| = 2^{2k−2} · (2^{2k−1} − 1) · numerator(4B_{2k}/k)
// for k ≥ 2 — the same Bernoulli numbers as im J. Equivalent to the common
// form with a_k·numerator(B_{2k}/k), a_k = 2 (k odd), 1 (k even), since
// numerator(4B_{2k}/k) = a_k·numerator(B_{2k}/k) (red leg, checked k ≤ 20).
// bP₄ = 0, so k = 1 is excluded.
export function bP(k) {
  if (k < 2) throw new Error('bP formula holds for k ≥ 2 (bP₄ = 0)');
  const B = bernoulli(2 * k)[2 * k];
  let [num] = mul(rat(4), div(B, rat(k)));
  if (num < 0n) num = -num;
  return 2n ** BigInt(2 * k - 2) * (2n ** BigInt(2 * k - 1) - 1n) * num;
}

// ---------- height-n cardinality of BG ----------
// Ben-Moshe–Carmeli–Schlank–Yanovski: at height n (E_n / T(n)-local) the
// semiadditive cardinality of a π-finite p-space A is the homotopy
// cardinality of the n-fold free loop space LⁿA. For A = BG,
// LⁿBG ≃ Hom(ℤⁿ, G)//G, so |BG|ₙ = |Hom(ℤⁿ, G)| / |G|.
// Groups are given as full element lists with a multiplication.
export function commutingTuples(G, mulG, n) {
  if (n === 0) return 1;
  const commutes = (a, b) => key(mulG(a, b)) === key(mulG(b, a));
  let count = 0;
  const rec = (chosen) => {
    if (chosen.length === n) { count++; return; }
    for (const g of G) if (chosen.every(h => commutes(g, h))) rec([...chosen, g]);
  };
  rec([]);
  return count;
}
// |BG|ₙ as an exact rational [num, den].
export const heightCardinality = (G, mulG, n) => rat(commutingTuples(G, mulG, n), G.length);

export function conjugacyClasses(G, mulG, invG) {
  const seen = new Set(); const classes = [];
  for (const g of G) {
    if (seen.has(key(g))) continue;
    const cls = new Map();
    for (const h of G) { const c = mulG(mulG(h, g), invG(h)); cls.set(key(c), c); }
    for (const k of cls.keys()) seen.add(k);
    classes.push([...cls.values()]);
  }
  return classes;
}
export const centralizer = (G, mulG, g) =>
  G.filter(h => key(mulG(g, h)) === key(mulG(h, g)));

// The loop-space recursion |BG|ₙ₊₁ = Σ_{[g]} |BC(g)|ₙ, computed independently.
export function heightCardinalityByLoops(G, mulG, invG, n) {
  if (n === 0) return rat(1, G.length);
  let s = rat(0);
  for (const cls of conjugacyClasses(G, mulG, invG)) {
    const C = centralizer(G, mulG, cls[0]);
    s = add(s, heightCardinalityByLoops(C, mulG, invG, n - 1));
  }
  return s;
}

// Small groups as permutation groups.
export const cyclic = n => [...Array(n).keys()].map(r => [...Array(n).keys()].map(i => (i + r) % n));
export const dihedral4 = () => closure([[1, 2, 3, 0], [0, 3, 2, 1]], 4);
export const quaternion8 = () => {
  // Q8 acting on itself by left multiplication; elements ±1, ±i, ±j, ±k indexed 0..7
  const names = ['1', '-1', 'i', '-i', 'j', '-j', 'k', '-k'];
  const table = { '1': { '1': '1', i: 'i', j: 'j', k: 'k' }, i: { '1': 'i', i: '-1', j: 'k', k: '-j' },
    j: { '1': 'j', i: '-k', j: '-1', k: 'i' }, k: { '1': 'k', i: 'j', j: '-i', k: '-1' } };
  const split = x => (x[0] === '-' ? [-1, x.slice(1)] : [1, x]);
  const m = (x, y) => {
    const [sx, bx] = split(x), [sy, by] = split(y); const r = table[bx][by];
    const [sr, br] = split(r); return (sx * sy * sr === 1 ? '' : '-') + br;
  };
  const gi = names.indexOf('i'), gj = names.indexOf('j');
  const perm = a => names.map(y => names.indexOf(m(names[a], y)));
  return closure([perm(gi), perm(gj)], 8);
};

// p-adic (chromatic) count for a general finite G: commuting n-tuples of
// p-power-order elements, |Hom(ℤ_pⁿ, G)| / |G| (HKR). Equals the integral
// count when G is a p-group.
export function elementOrder(g, mulG) {
  const id = g.map((_, i) => i); let x = g, k = 1;
  while (key(x) !== key(id)) { x = mulG(x, g); k++; }
  return k;
}
const isPowerOf = (n, p) => { while (n % p === 0) n /= p; return n === 1; };
export function pAdicHeightCardinality(G, mulG, n, p) {
  const Gp = G.filter(g => isPowerOf(elementOrder(g, mulG), p));
  if (n === 0) return rat(1, G.length);
  const commutes = (a, b) => key(mulG(a, b)) === key(mulG(b, a));
  let count = 0;
  const rec = chosen => {
    if (chosen.length === n) { count++; return; }
    for (const g of Gp) if (chosen.every(h => commutes(g, h))) rec([...chosen, g]);
  };
  rec([]);
  return rat(count, G.length);
}
